version: '3.1'

services:
  mongo:
    container_name: sample_mongo
    image: mongo
    restart: always
    env_file: .env
    ports:
      - 57017:27017
    volumes:
      - mongo_data:/data/db
      - ./volumes/mongo/backup:/backup

  mongo-express:
    image: mongo-express
    restart: always
    env_file: .env
    ports:
      - 58081:8081

  dind-cron:
    build: .docker/dind-cron
    restart: always
    env_file: .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongo_data:
    driver: 'local'
